logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /tmp/myapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    severity-to-level:
      type: modify_fields
      fields:
        severity:
          from: level
          to: JsonPayload.severity
          action: update
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, severity-to-level]