name: Validate Packer Template
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"
      - name: Set up Java 17 to create target directory for Packer
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: fix permissions
        run: chmod +x mvnw
      - name: Build with Maven to create target directory for Packer
        run: ./mvnw clean compile
      - name: Init Packer Template
        run: packer init ./packer/webapp-image.pkr.hcl
      - name: Validate Packer Template
        run: packer validate ./packer/webapp-image.pkr.hcl