name: Run Integration Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: run Mysql
        run: sudo systemctl start mysql
      - name: fix permissions
        run: chmod +x mvnw
      - name: Run Tests with Maven
        run: ./mvnw test